# Generated by Django 3.1.6 on 2021-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
