# Generated by Django 3.1.11 on 2021-05-17 21:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
