# Generated by Django 3.1.6 on 2021-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_host',
            field=models.BooleanField(default=False, help_text='Check only if you intend on hosting a job board', verbose_name='Hosting a Job Board'),
        ),
    ]
